app <- ShinyDriver$new("../")
app$snapshotInit("initial_test")

app$setInputs(session = "Full Plot")
app$snapshot()
app$setInputs(session = "Confidence Intervals")
app$snapshot()
app$setInputs(session = "Autocorrelation tests")
app$snapshot()
app$setInputs(session = "Full Plot")
app$setInputs(control = "Scotland")
app$setInputs(obRange = c(1993, 2016))
app$setInputs(obRange = c(1992, 2016))
app$setInputs(p = 1)
app$snapshot()
